2024-02-29 22:36:00,891 INFO    StreamThr :67648 [internal.py:wandb_internal():86] W&B internal server running at pid: 67648, started at: 2024-02-29 22:36:00.889939
2024-02-29 22:36:00,893 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: status
2024-02-29 22:36:00,899 INFO    WriterThread:67648 [datastore.py:open_for_write():87] open: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/run-e2dwiu7n.wandb
2024-02-29 22:36:00,901 DEBUG   SenderThread:67648 [sender.py:send():382] send: header
2024-02-29 22:36:01,234 DEBUG   SenderThread:67648 [sender.py:send():382] send: run
2024-02-29 22:36:06,235 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: keepalive
2024-02-29 22:36:11,235 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: keepalive
2024-02-29 22:36:16,236 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: keepalive
2024-02-29 22:36:21,237 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: keepalive
2024-02-29 22:36:26,237 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: keepalive
2024-02-29 22:36:29,261 INFO    SenderThread:67648 [dir_watcher.py:__init__():211] watching files in: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files
2024-02-29 22:36:29,261 INFO    SenderThread:67648 [sender.py:_start_run_threads():1136] run started: e2dwiu7n with start time 1709217360.895624
2024-02-29 22:36:29,262 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: status_report
2024-02-29 22:36:29,271 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: check_version
2024-02-29 22:36:29,272 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: check_version
2024-02-29 22:36:30,098 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: run_start
2024-02-29 22:36:30,108 DEBUG   HandlerThread:67648 [system_info.py:__init__():27] System info init
2024-02-29 22:36:30,108 DEBUG   HandlerThread:67648 [system_info.py:__init__():42] System info init done
2024-02-29 22:36:30,109 INFO    HandlerThread:67648 [system_monitor.py:start():194] Starting system monitor
2024-02-29 22:36:30,109 INFO    SystemMonitor:67648 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-29 22:36:30,110 INFO    HandlerThread:67648 [system_monitor.py:probe():214] Collecting system info
2024-02-29 22:36:30,110 INFO    SystemMonitor:67648 [interfaces.py:start():190] Started cpu monitoring
2024-02-29 22:36:30,112 INFO    SystemMonitor:67648 [interfaces.py:start():190] Started disk monitoring
2024-02-29 22:36:30,114 INFO    SystemMonitor:67648 [interfaces.py:start():190] Started gpu monitoring
2024-02-29 22:36:30,115 INFO    SystemMonitor:67648 [interfaces.py:start():190] Started memory monitoring
2024-02-29 22:36:30,116 INFO    SystemMonitor:67648 [interfaces.py:start():190] Started network monitoring
2024-02-29 22:36:30,162 DEBUG   HandlerThread:67648 [system_info.py:probe():151] Probing system
2024-02-29 22:36:30,175 DEBUG   HandlerThread:67648 [system_info.py:_probe_git():136] Probing git
2024-02-29 22:36:30,208 DEBUG   HandlerThread:67648 [system_info.py:_probe_git():144] Probing git done
2024-02-29 22:36:30,209 DEBUG   HandlerThread:67648 [system_info.py:probe():199] Probing system done
2024-02-29 22:36:30,209 DEBUG   HandlerThread:67648 [system_monitor.py:probe():223] {'os': 'Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17', 'python': '3.9.18', 'heartbeatAt': '2024-02-29T14:36:30.163135', 'startedAt': '2024-02-29T14:36:00.857414', 'docker': None, 'cuda': None, 'args': ('--lora_enable', 'True', '--lora_r', '128', '--lora_alpha', '256', '--mm_projector_lr', '0', '--deepspeed', './scripts/deepspeed/zero3.json', '--model_name_or_path', '/mnt/petrelfs/songmingyang/songmingyang/model/others/llava-v1.5-7b', '--version', 'v1', '--data_path', '/mnt/petrelfs/songmingyang/songmingyang/runs/llava/test/merged/llava_multilingual_dpo_data.jsonl', '--vision_tower', '/mnt/petrelfs/songmingyang/songmingyang/model/others/clip-vit-large-patch14-336', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', '/mnt/petrelfs/songmingyang/songmingyang/runs/llava/dpo/checkpoints/llava-v1_5', '--num_train_epochs', '1', '--per_device_train_batch_size', '16', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '50000', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--warmup_steps', '0', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True', '--report_to', 'wandb', '--run_name', 'llava-v1.5', '--beta', '0.1'), 'state': 'running', 'program': '/mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/./train_dpo.py', 'codePathLocal': 'train_dpo.py', 'codePath': 'mhr/alignment/models/llava-v1_5/train_dpo.py', 'git': {'remote': 'git@github.com:ssmisya/mhr.git', 'commit': '110501a9e66d90fbda2b9d422d21d3425af39af7'}, 'email': 'hitsmy@qq.com', 'root': '/mnt/petrelfs/songmingyang/code/mm/MAPO', 'host': 'SH-IDCA1404-10-140-54-120', 'username': 'songmingyang', 'executable': '/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}, {'current': 3400.0, 'min': 800.0, 'max': 3400.0}], 'disk': {'/': {'total': 488.89007568359375, 'used': 304.85155868530273}}, 'gpu': 'NVIDIA A100-SXM4-80GB', 'gpu_count': 8, 'gpu_devices': [{'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85899345920}], 'memory': {'total': 1007.3445129394531}}
2024-02-29 22:36:30,210 INFO    HandlerThread:67648 [system_monitor.py:probe():224] Finished collecting system info
2024-02-29 22:36:30,210 INFO    HandlerThread:67648 [system_monitor.py:probe():227] Publishing system info
2024-02-29 22:36:30,211 DEBUG   HandlerThread:67648 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-02-29 22:36:30,264 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_created():271] file/dir created: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/conda-environment.yaml
2024-02-29 22:36:34,045 DEBUG   HandlerThread:67648 [system_info.py:_save_conda():220] Saving conda packages done
2024-02-29 22:36:34,048 INFO    HandlerThread:67648 [system_monitor.py:probe():229] Finished publishing system info
2024-02-29 22:36:34,062 DEBUG   SenderThread:67648 [sender.py:send():382] send: files
2024-02-29 22:36:34,063 INFO    SenderThread:67648 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-02-29 22:36:34,069 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: python_packages
2024-02-29 22:36:34,069 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: python_packages
2024-02-29 22:36:34,070 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: stop_status
2024-02-29 22:36:34,070 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-29 22:36:34,072 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: stop_status
2024-02-29 22:36:34,272 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_created():271] file/dir created: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/wandb-metadata.json
2024-02-29 22:36:34,273 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_created():271] file/dir created: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/requirements.txt
2024-02-29 22:36:34,619 DEBUG   SenderThread:67648 [sender.py:send():382] send: telemetry
2024-02-29 22:36:34,619 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: status_report
2024-02-29 22:36:34,620 DEBUG   SenderThread:67648 [sender.py:send():382] send: config
2024-02-29 22:36:34,621 DEBUG   SenderThread:67648 [sender.py:send():382] send: metric
2024-02-29 22:36:34,622 DEBUG   SenderThread:67648 [sender.py:send():382] send: telemetry
2024-02-29 22:36:34,622 DEBUG   SenderThread:67648 [sender.py:send():382] send: metric
2024-02-29 22:36:34,622 WARNING SenderThread:67648 [sender.py:send_metric():1354] Seen metric with glob (shouldn't happen)
2024-02-29 22:36:34,905 DEBUG   SenderThread:67648 [sender.py:send():382] send: exit
2024-02-29 22:36:34,906 INFO    SenderThread:67648 [sender.py:send_exit():589] handling exit code: 1
2024-02-29 22:36:34,906 INFO    SenderThread:67648 [sender.py:send_exit():591] handling runtime: 4
2024-02-29 22:36:34,911 INFO    SenderThread:67648 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-02-29 22:36:34,911 INFO    SenderThread:67648 [sender.py:send_exit():597] send defer
2024-02-29 22:36:34,912 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:34,912 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 0
2024-02-29 22:36:34,913 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:34,913 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 0
2024-02-29 22:36:34,913 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 1
2024-02-29 22:36:34,914 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:34,914 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 1
2024-02-29 22:36:34,915 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:34,915 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 1
2024-02-29 22:36:34,915 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 2
2024-02-29 22:36:34,916 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:34,916 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 2
2024-02-29 22:36:34,917 INFO    HandlerThread:67648 [system_monitor.py:finish():203] Stopping system monitor
2024-02-29 22:36:34,917 DEBUG   SystemMonitor:67648 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-29 22:36:34,917 INFO    HandlerThread:67648 [interfaces.py:finish():202] Joined cpu monitor
2024-02-29 22:36:34,918 DEBUG   SystemMonitor:67648 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-29 22:36:34,918 INFO    HandlerThread:67648 [interfaces.py:finish():202] Joined disk monitor
2024-02-29 22:36:34,919 DEBUG   SystemMonitor:67648 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-29 22:36:35,276 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_created():271] file/dir created: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/output.log
2024-02-29 22:36:35,277 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_created():271] file/dir created: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/wandb-summary.json
2024-02-29 22:36:35,787 INFO    HandlerThread:67648 [interfaces.py:finish():202] Joined gpu monitor
2024-02-29 22:36:35,787 INFO    HandlerThread:67648 [interfaces.py:finish():202] Joined memory monitor
2024-02-29 22:36:35,788 INFO    HandlerThread:67648 [interfaces.py:finish():202] Joined network monitor
2024-02-29 22:36:35,789 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:35,789 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 2
2024-02-29 22:36:35,789 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 3
2024-02-29 22:36:35,790 DEBUG   SenderThread:67648 [sender.py:send():382] send: stats
2024-02-29 22:36:35,790 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:35,791 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 3
2024-02-29 22:36:35,792 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:35,792 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 3
2024-02-29 22:36:35,793 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 4
2024-02-29 22:36:35,793 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:35,794 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 4
2024-02-29 22:36:35,794 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:35,795 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 4
2024-02-29 22:36:35,795 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 5
2024-02-29 22:36:35,795 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:35,796 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 5
2024-02-29 22:36:35,796 DEBUG   SenderThread:67648 [sender.py:send():382] send: summary
2024-02-29 22:36:35,798 INFO    SenderThread:67648 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-02-29 22:36:35,799 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:35,800 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 5
2024-02-29 22:36:35,800 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 6
2024-02-29 22:36:35,801 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:35,801 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 6
2024-02-29 22:36:35,802 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:35,802 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 6
2024-02-29 22:36:35,806 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: status_report
2024-02-29 22:36:35,906 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: poll_exit
2024-02-29 22:36:36,193 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 7
2024-02-29 22:36:36,194 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: poll_exit
2024-02-29 22:36:36,194 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:36,195 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 7
2024-02-29 22:36:36,195 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:36,196 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 7
2024-02-29 22:36:36,279 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_modified():288] file/dir modified: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/wandb-summary.json
2024-02-29 22:36:36,280 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_modified():288] file/dir modified: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/config.yaml
2024-02-29 22:36:36,638 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 8
2024-02-29 22:36:36,639 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:36,639 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 8
2024-02-29 22:36:36,640 DEBUG   SenderThread:67648 [sender.py:send_request():409] send_request: defer
2024-02-29 22:36:36,641 INFO    SenderThread:67648 [sender.py:send_request_defer():613] handle sender defer: 8
2024-02-29 22:36:36,641 INFO    SenderThread:67648 [job_builder.py:build():296] Attempting to build job artifact
2024-02-29 22:36:36,643 INFO    SenderThread:67648 [job_builder.py:_get_source_type():426] is repo sourced job
2024-02-29 22:36:36,702 INFO    SenderThread:67648 [job_builder.py:build():402] adding wandb-job metadata file
2024-02-29 22:36:36,719 INFO    SenderThread:67648 [sender.py:transition_state():617] send defer: 9
2024-02-29 22:36:36,720 DEBUG   SenderThread:67648 [sender.py:send():382] send: artifact
2024-02-29 22:36:36,720 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: defer
2024-02-29 22:36:36,723 INFO    HandlerThread:67648 [handler.py:handle_request_defer():172] handle defer: 9
2024-02-29 22:36:36,906 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: poll_exit
2024-02-29 22:36:37,282 INFO    Thread-12 :67648 [dir_watcher.py:_on_file_modified():288] file/dir modified: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/output.log
2024-02-29 22:36:41,907 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: keepalive
2024-02-29 22:36:46,909 DEBUG   HandlerThread:67648 [handler.py:handle_request():146] handle_request: keepalive
2024-02-29 22:36:49,943 WARNING StreamThr :67648 [internal.py:is_dead():414] Internal process exiting, parent pid 61399 disappeared
2024-02-29 22:36:49,943 ERROR   StreamThr :67648 [internal.py:wandb_internal():152] Internal process shutdown.
2024-02-29 22:36:50,908 INFO    WriterThread:67648 [datastore.py:close():296] close: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/run-e2dwiu7n.wandb
2024-02-29 22:36:50,910 INFO    HandlerThread:67648 [handler.py:finish():869] shutting down handler
2024-02-29 22:37:00,573 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:00,573 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:00,573 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:00,573 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:37:00,574 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:37:00,574 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:37:00,574 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:00,575 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:00,575 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:01,724 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:01,725 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:37:01,725 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:01,777 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:01,778 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:37:01,778 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:01,782 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:01,783 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:37:01,783 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:03,959 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:03,960 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:37:03,960 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:03,961 INFO    wandb-upload_1:67648 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 779, in urlopen
    self._prepare_proxy(conn)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1048, in _prepare_proxy
    conn.connect()
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connection.py", line 633, in connect
    self._tunnel()  # type: ignore[attr-defined]
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/http/client.py", line 930, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 500 Internal Server Error

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-02-29 22:37:04,147 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:04,148 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:37:04,148 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:04,149 INFO    wandb-upload_0:67648 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 779, in urlopen
    self._prepare_proxy(conn)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1048, in _prepare_proxy
    conn.connect()
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connection.py", line 633, in connect
    self._tunnel()  # type: ignore[attr-defined]
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/http/client.py", line 930, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 500 Internal Server Error

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-02-29 22:37:04,232 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:04,233 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:37:04,233 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:04,234 INFO    wandb-upload_2:67648 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 779, in urlopen
    self._prepare_proxy(conn)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1048, in _prepare_proxy
    conn.connect()
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connection.py", line 633, in connect
    self._tunnel()  # type: ignore[attr-defined]
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/http/client.py", line 930, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 500 Internal Server Error

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/petrelfs/songmingyang/anaconda3/envs/vcd/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-02-29 22:37:08,298 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:08,299 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:37:08,299 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:08,485 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:08,486 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:37:08,486 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:08,856 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:08,857 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:37:08,857 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:16,598 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:16,599 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:37:16,599 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:18,342 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:18,342 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:37:18,343 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:18,650 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:18,651 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:37:18,651 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:34,535 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:34,535 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:37:34,536 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:36,364 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:36,364 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:37:36,365 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:37:37,538 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:37:37,538 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:37:37,539 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:38:33,470 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:38:33,470 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:38:33,470 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:38:33,471 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:38:33,471 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:38:33,472 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:38:33,472 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:38:33,472 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:38:33,473 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:40:02,229 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:40:02,229 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:40:02,230 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:40:02,230 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:40:02,230 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:40:02,231 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:40:02,231 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:40:02,232 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:40:02,232 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:42:13,321 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/pjlab_moe/mhr/e2dwiu7n/wandb-metadata.json?Expires=1709303794&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ukf6k6tKdEIqg4rSQPmPeTXhbFl1fwSF%2BijE%2F95hyxmElt93QcfbNKL5D9tMVFdfs9Fy1t65L%2BrIbiTUAh7WI25PWcb%2B17YqWKDAKAeDfq3XhySJtLbkwd7h3sTN5KJk2s8ltNEy9MeSwuTzRm0R6mSosBaBOJMrxP%2BiEDITctBlohdx43QAMEHw9DhSy2hXR0YsIb2B57FDf5ET9J2RwRMc%2BIYXyD0UQqZZMqOs5QBqxdrTSgRP7O9EPiQ7GRHgFHFr2dGsDLUpM3VC%2FlUVfjHEMki3jiW2HYPy6lmCTjwBIM0VBMveQ2y0V6Gocdb6wKMl5Bbuod7PuKcwyCYmhA%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:42:13,321 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '17459'}
2024-02-29 22:42:13,322 ERROR   wandb-upload_0:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:42:13,490 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/a486eab3d3931b225a02b1dfe4127eef?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Y5vyyLIREOz8O4Q16Xc2Nna3YhJ2%2BRBcpdmlwZRp1WqhiCfkMDH56mQ760hMFAvbeCBwivSWOg6or7ntdW%2Fe71cakHfjzetLJ%2B7faJ45Zv0mCZHpRiV2ioKHhyK7ISvjoYD0l7Jj59awYK%2FmCk8GRLCJ0dMgHxegWTH0zb8j0U1k02r9fquSDRm3ruP8Yj6OdvW9SalPOgu0pc%2Bxb3NcaO9Ivlvxu%2Fv%2FisGt1KTarrgZywAm3gpeXEGnhP9ZlZTMN%2FPaup7kjSuMH%2Bk2H4tksnQYttabTuXmwg3nLaMs0Ba5zCsOTWGQZj5eAgnoA1oo2rjTtPP5sogryuh2vxzV3g%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:42:13,491 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'pIbqs9OTGyJaArHf5BJ+7w==', 'Content-Type': 'application/json', 'Content-Length': '20771'}
2024-02-29 22:42:13,491 ERROR   wandb-upload_2:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:42:16,399 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-artifacts-prod/wandb_artifacts/144129290/735385498/8ae21844c55c985421a89649f5138cd4?Expires=1709303798&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=i%2BkZqSxWunwzjlAw0sjLE6DjZFE8Ri%2BvXy5rmK1%2FvjA0YeRxjOrAhAB8lZLog7%2FTB7u3LDI5rfik0K49gRihBMkrCNcUCadzreI7x7raVtVC9XTCUpvLaH88vvyPxjvDIhLzP1rO5mF5Xd8TMTUKduL%2B%2Bht04smkDncBJOYUVLzlQSlg4kjUGVZu5AdvoVNx6kPJo5%2FDJO1YOf9aLJxOZl3y18uO5BcRHAUx1PFlR7KYp8dZPFzvtSJc%2FbPGsMzx%2BhbqKTktSFZf0igRE53BPrdYPpamIgVfNtE5mP4iM%2B%2BZnKvUzvxrL5mXR%2FpJkKJJiQ0VfolWuEAw%2F3xJpidwwQ%3D%3D (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 500 Internal Server Error')))
2024-02-29 22:42:16,400 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'iuIYRMVcmFQhqJZJ9ROM1A==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '2886'}
2024-02-29 22:42:16,400 ERROR   wandb-upload_1:67648 [internal_api.py:upload_file():2769] upload_file response body: 
2024-02-29 22:47:12,021 INFO    wandb-upload_2:67648 [upload_job.py:push():89] Uploaded file /mnt/petrelfs/songmingyang/.local/share/wandb/artifacts/staging/tmp1h135qzd
2024-02-29 22:47:14,582 INFO    wandb-upload_0:67648 [upload_job.py:push():131] Uploaded file /tmp/tmp1_okwendwandb/6fany3vi-wandb-metadata.json
2024-02-29 22:47:26,929 INFO    wandb-upload_1:67648 [upload_job.py:push():89] Uploaded file /mnt/petrelfs/songmingyang/.local/share/wandb/artifacts/staging/tmpekeb_scd
2024-02-29 22:47:52,841 INFO    SenderThread:67648 [sender.py:send_artifact():1494] sent artifact job-git_github.com_ssmisya_mhr.git_mhr_alignment_models_llava-v1_5_train_dpo.py - {'id': 'QXJ0aWZhY3Q6NzM1Mzg1NDk4', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjE0NDEyOTI5MA==', 'latestArtifact': None}}
2024-02-29 22:47:52,842 INFO    SenderThread:67648 [sender.py:finish():1572] shutting down sender
2024-02-29 22:47:52,842 INFO    SenderThread:67648 [dir_watcher.py:finish():358] shutting down directory watcher
2024-02-29 22:47:53,338 INFO    SenderThread:67648 [dir_watcher.py:finish():388] scan: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files
2024-02-29 22:47:53,339 INFO    SenderThread:67648 [dir_watcher.py:finish():402] scan save: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/config.yaml config.yaml
2024-02-29 22:47:53,340 INFO    SenderThread:67648 [dir_watcher.py:finish():402] scan save: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/output.log output.log
2024-02-29 22:47:53,341 INFO    SenderThread:67648 [dir_watcher.py:finish():402] scan save: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/wandb-metadata.json wandb-metadata.json
2024-02-29 22:47:53,341 INFO    SenderThread:67648 [dir_watcher.py:finish():402] scan save: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/wandb-summary.json wandb-summary.json
2024-02-29 22:47:53,342 INFO    SenderThread:67648 [dir_watcher.py:finish():402] scan save: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/conda-environment.yaml conda-environment.yaml
2024-02-29 22:47:53,343 INFO    SenderThread:67648 [dir_watcher.py:finish():402] scan save: /mnt/petrelfs/songmingyang/code/mm/MAPO/mhr/alignment/models/llava-v1_5/wandb/run-20240229_223600-e2dwiu7n/files/requirements.txt requirements.txt
2024-02-29 22:47:53,344 INFO    SenderThread:67648 [file_pusher.py:finish():172] shutting down file pusher
2024-02-29 22:47:53,344 INFO    SenderThread:67648 [file_pusher.py:join():178] waiting for file pusher
2024-02-29 22:47:53,345 INFO    SenderThread:67648 [file_stream.py:finish():595] file stream finish called
2024-02-29 22:47:53,951 INFO    SenderThread:67648 [file_stream.py:finish():599] file stream finish is done
